# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# Node.js
# This section defines the Azure Pipeline configuration for a Node.js project.
# It includes instructions for building the project using npm and saving the build artifacts.

# The trigger section specifies which branches will trigger the pipeline when new commits are pushed.
trigger:
  branches:
    include:
      - "master"
  tags:
    include:
      - "release/**"
      - "qa/**"
      - "dev/**"

# The pool section specifies the agent pool that will run the jobs in this pipeline.
# 'Default' is typically the name of the Microsoft-hosted agent pool provided by Azure DevOps.
pool:
  name: Default-Modern

# The stages section allows you to organize the pipeline into multiple stages.
# Here we have only one stage named 'build', which contains the jobs for building the project.
stages:
  - stage: build
    # Within the build stage, we define the jobs that need to be run.
    # Each job runs independently and can run on different agents if required.
    # The 'build' stage is responsible for executing tasks that compile and build the code.
    jobs:
      - job: installAndBuild
        displayName: Install and Build
        steps:
          # Install the LTS version of Node
          - task: UseNode@1
            name: use_node
            displayName: Install Node
            inputs:
              version: 24.X

          - task: Npm@1
            name: setup_bun
            displayName: setup bun
            inputs:
              command: 'custom'
              customCommand: 'install -g bun'
              verbose: true

          # Install dependencies
          - script: |
              bun ci
            name: install
            displayName: "bun install"

          # Install dependencies and build the project
          - script: |
              bun run build-and-tsc
            name: build
            displayName: "Build"

          - script: |
              bun run test
            name: test
            displayName: "Unit Test"

          # Count the number of files in the 'dist' folder
          # to make sure there are actually files there.
          # This script will return a non-zero exit code
          # if there are no files.
          - script: |
              bun -b tools/count-files.js
            name: count_files
            displayName: "Count files"

          - task: PublishTestResults@2
            name: publish_test_results
            displayName: Publish Test Results
            condition: succeededOrFailed()
            continueOnError: true
            inputs:
              searchFolder: ./test-results
              testResultsFiles: test-results.xml

          # This task is disabled for the moment because enabling coverage causes
          # the unit test to run forever after mocking was added.
          # The issue is that mocking is not implemented for all URLs, so once that
          # has been completed then this task can be enabled again.
          - task: PublishCodeCoverageResults@2
            enabled: false
            name: publish_code_coverage
            displayName: Publish Code Coverage
            continueOnError: true
            inputs:
              summaryFileLocation: coverage/cobertura-coverage.xml

          # Copy the build output (dist folder) to the staging directory for artifact publishing.
          - task: CopyFiles@2
            name: copy_files
            displayName: Copy Files to $(Build.ArtifactStagingDirectory)
            inputs:
              # The target folder to copy files to, typically a staging directory for artifacts.
              TargetFolder: $(Build.ArtifactStagingDirectory)
              # The contents to copy, in this case, everything from the 'dist' folder.
              Contents: dist/**

          # Publish the build artifacts to Azure Pipelines.
          - task: PublishBuildArtifacts@1
            name: publish_build_artifacts
            displayName: Publish Build Artifacts
            inputs:
              # The path to the folder containing build artifacts to publish.
              PathtoPublish: $(Build.ArtifactStagingDirectory)
              # The name for this artifact, which can be used for deployment or reference.
              ArtifactName: www
