version: "0.2"
useGitignore: true
ignorePaths: []
allowCompoundWords: true
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
dictionaries:
  - custom-dictionary
words: []
ignoreWords:
  - JURLBL
  - LDNM
  - daltonic
import: []
